# Generated by Django 3.2.9 on 2022-07-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotInfo',
            fields=[
                ('robotID', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('heading', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('angle', models.IntegerField(blank=True, null=True)),
                ('left_motor', models.IntegerField(blank=True, null=True)),
                ('right_motor', models.IntegerField(blank=True, null=True)),
                ('reward_data', models.IntegerField(blank=True, null=True)),
                ('action_data', models.CharField(max_length=255)),
                ('stabilization', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotAvailability',
            fields=[
                ('robotId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.robotinfo')),
                ('availabile', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
