# Generated by Django 3.2.9 on 2022-07-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customjsonform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customjsonform',
            name='customer_input_data',
        ),
    ]
