# Generated by Django 3.2.9 on 2022-07-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customjsonform'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_robots', models.IntegerField(blank=True, null=True)),
                ('number_of_loops', models.IntegerField(blank=True, null=True)),
                ('list_of_commands', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomJsonForm',
        ),
    ]
